{
  imports = [
    ./aerospace.nix
    ./albert.nix
    ./atuin.nix
    ./bat.nix
    ./browser.nix
    ./btop.nix
    ./carapace.nix
    ./direnv.nix
    ./discord.nix
    ./easyeffects.nix
    ./firefox.nix
    ./fish.nix
    ./flameshot.nix
    ./fuzzel.nix
    ./ghostty.nix
    ./git.nix
    ./gnome.nix
    ./helix.nix
    ./homelab.nix
    ./jujutsu.nix
    ./keebs.nix
    ./kitty.nix
    ./lutris.nix
    ./nautilus.nix
    ./nemo.nix
    ./nvim.nix
    ./ranger.nix
    ./ssh.nix
    ./starsector.nix
    ./starship.nix
    ./swaylock.nix
    ./swappy.nix
    ./thunar.nix
    ./tmux.nix
    ./vicinae.nix
    ./walker.nix
    ./wezterm.nix
    ./yazi.nix
    ./zed-editor.nix
    ./zellij.nix
    ./zoxide.nix
  ];
}
