keys:
  - &user:
    - &dusty age1d0p4d7we2z424gs2xste7djkn7f5rqqhf4r4e92gy9v6ewqtzv6snfs404
  - &hosts:
    - &jezrien age1zrsq6443zacdx3tpsfryeg2t5wqxz465cxezmar4qu8zgh00v5fsc8vypu
    - &taln age1kah7ss6eay00u8j95lul79u2rkfqml5r9fe7jetemlhhrvpztfrs6gvz85
    - &taldain age10qrd4ws96e6wd6gtel3pp99mhw4k6gpf9q6st8wp6yk0v7hsvewqpg063k
    - &homelab age1y4rkzxjql65p2vl68dy73ly0ga864u287mur9l60m4xspucj353q276ss0
    - &work-macbook age1a2dsa5sk4xnl8m8vdahhl0h7v54n89nzp4jesuk0mn79ck4ukdjsjuyuax

creation_rules:
  - path_regex: modules/hosts/jezrien/secrets.yaml$
    key_groups:
      - age:
          - *dusty
          - *jezrien
  - path_regex: taln/secrets.yaml$
    key_groups:
      - age:
          - *dusty
          - *taln
  - path_regex: homelab/secrets.yaml$
    key_groups:
      - age:
          - *dusty
          - *homelab
