#!/usr/bin/fish

# fix xrdb
#xrdb -I$HOME/.dotfiles/configs/x/ $HOME/.Xresources
update_xrdb

# set our background
feh --bg-fill ~/.desktop_bg

# increase key repeat rate
xset r rate 190 40

# disable screen blanking
# xset s off         # don't activate screensaver
# xset -dpms         # disable DPMS (Energy Star) features.
# xset s noblank     # don't blank the video device

# start urxvt daemon
urxvtd -q -o -f

# start xbindkeys
xbindkeys

# start compton, -C to remove shadow on docks (e.g. latte-dock)
# compton --config ~/.dotfiles/configs/compton.conf -b -C

# start the bar
polybar -q -r top & disown
# $HOME/.dotfiles/configs/lemonbar/start_lemonbar.sh &

# call screenlayout script file if present
if test -e ~/.screenlayout.sh
  echo calling screenlayout
  ~/.screenlayout.sh
end

autocutsel -selection CLIPBOARD -fork
autocutsel -selection PRIMARY -fork

# source the home file
# use this to start an app for only one machine (for example, kodi/xbmc)
. ~/.autostart.local
