#!/bin/bash

# check if we're already locked... if we are, no need to do anything!
# (this is done because xautolock just calls this script every so often)
if ! pgrep i3lock >/dev/null 2>&1; then
  sleep 0.5
  scrot ~/.tmp/screenshot.png
  convert -scale 10% -scale 1000% ~/.tmp/screenshot.png ~/.tmp/screenshotblur.png
  composite -gravity center $HOME/.dotfiles/configs/i3/assets/lockiconsml.png ~/.tmp/screenshotblur.png ~/.tmp/screenshotblur.png
  # -n = no-fork, so this script knows when the screen is unlocked and we can then forcibly kill i3lock
  i3lock -n -i ~/.tmp/screenshotblur.png
  killall i3lock >/dev/null 2>&1
fi
