{ ... }: {
  wayland.windowManager.hyprland.settings = {
    windowrulev2 = [
      "float, class:(1Password)"
      "float, class:(com.github.iwalton3.jellyfin-media-player)"
      "float, class:(com.mitchellh.ghostty)"
      "float, class:(com.obsproject.Studio)"
      "float, class:(dev.zed.Zed)"
      "float, class:(galculator)"
      "float, class:(neovide)"
      "float, class:(nemo)"
      "float, class:(obsidian)"
      "float, class:(opentrack)"
      "float, class:(org.gnome.baobab)"
      "float, class:(org.telegram.desktop)"
      "float, class:(thunar)"
      "float, class:(pavucontrol)"
      "float, class:(ristretto) # image viewer"
      "float, class:(Spotify)"
      "float, class:(virt-manager)"
      "float, class:(vlc)"
      "float, class:(yad)"
      "float, class:(zenity)"
      "float, class:zen-beta,title:Picture-in-Picture"
      "float, class:(net.lutris.Lutris)"
      "size 1920 1080, class:(net.lutris.Lutris)"
      "float, class:^org.telegram.desktop$, title:^Media viewer$"
      "float, class:net.davidotek.pupgui2"
      "workspace 4 silent, class:(discord)"
      "workspace 4 silent, class:^(steam)$"
      "workspace 4 silent, title:(Friends List)"
      "float, class:(steam), title:(Friends List)"
      "stayfocused, title:^()$,class:^(steam)$"
      "minsize 1 1, title:^()$,class:^(steam)$"
      "workspace $gamingWorkspace, class:(dota2)"
      "workspace $gamingWorkspace, class:^(RimWorldLinux)$"
      "workspace $steamWorkspace silent, class:^(steam_app_8500)$,title:^(EVE Launcher)$,initialClass:^(steam_app_8500)$,initialTitle:^(EVE Launcher)$"
      "fullscreenstate:2 -1, initialTitle:^(EVE)$"
      "workspace $gamingWorkspace, class:(Project Zomboid)"
      "fullscreen, class:(Project Zomboid)"
      "workspace $gamingWorkspace, class:(X4)"
    ];
  };
}
