###### misc
# separator between panel items
PANEL_SEP=" "
PANEL_SEP_ELLIPS=""

### icons
# performance icons
ICON_CPU="" # tachometer
ICON_MEMORY=""
ICON_DISK="" # bar chart
ICON_DISK_ALT="" # bank
ICON_BATTERY_0=""
ICON_BATTERY_0_ALT="" # ambulance
ICON_BATTERY_25=""
ICON_BATTERY_50=""
ICON_BATTERY_75=""
ICON_BATTERY_100=""
# misc icons
ICON_CALENDAR=""
ICON_CLOCK=""
ICON_CODE="" # github
ICON_GAME=""
ICON_FIREFOX=""
ICON_NETWORK_ETH="" # cloud
ICON_NETWORK_WIFI=""
ICON_TERM="" # ">_"
ICON_VOLUME=""
ICON_VOLUME_LOW=""
ICON_VOLUME_MUTE=""
ICON_WORKSPACES=""

# colors
COLOR_FOREGROUND="#FFBEB292"
COLOR_BACKGROUND="#FF262626"
COLOR_ACTIVE_WORKSPACE="#FF574F49"
COLOR_ACTIVE_WORKSPACE_INDICATOR="#FFCB4030"
COLOR_WARN="#FFCA9A2C"
