###### misc
# separator between panel items
PANEL_SEP=" "
PANEL_SEP_ELLIPS=""

### icons
# performance icons
ICON_CPU="" # tachometer
ICON_MEMORY=""
ICON_DISK="" # bar chart
ICON_DISK_ALT="" # bank
ICON_BATTERY_0=""
ICON_BATTERY_0_ALT="" # ambulance
ICON_BATTERY_25=""
ICON_BATTERY_50=""
ICON_BATTERY_75=""
ICON_BATTERY_100=""
# misc icons
ICON_CALENDAR=""
ICON_CLOCK=""
ICON_CODE="" # github
ICON_GAME=""
ICON_FIREFOX=""
ICON_NETWORK_ETH="" # cloud
ICON_NETWORK_WIFI=""
ICON_TERM="" # ">_"
ICON_VOLUME=""
ICON_VOLUME_LOW=""
ICON_VOLUME_MUTE=""
ICON_WORKSPACES=""

# colors
COLOR_FOREGROUND='#FFEBDBB2'
COLOR_BACKGROUND='#FF282828'
COLOR_ACTIVE_MONITOR_FG='#FFEBDBB2'
COLOR_ACTIVE_MONITOR_BG='#FF282828'
COLOR_INACTIVE_MONITOR_FG='#FFEBDBB2'
COLOR_INACTIVE_MONITOR_BG='#FF34322E'
COLOR_FOCUSED_OCCUPIED_FG='#FFEBDBB2'
COLOR_FOCUSED_OCCUPIED_BG='#FF282828'
COLOR_FOCUSED_FREE_FG='#FF28211C'
COLOR_FOCUSED_FREE_BG='#FF98971A'
COLOR_FOCUSED_URGENT_FG='#FF28211C'
COLOR_FOCUSED_URGENT_BG='#FFD79921'
COLOR_OCCUPIED_FG='#FFEBDBB2'
COLOR_OCCUPIED_BG='#FF282828'
COLOR_FREE_FG='#FF28211C'
COLOR_FREE_BG='#FF98971A'
COLOR_URGENT_FG='#FF28211C'
COLOR_URGENT_BG='#FFD79921'
COLOR_LAYOUT_FG='#FFEBDBB2'
COLOR_LAYOUT_BG='#FF282828'
COLOR_TITLE_FG='#FFEBDBB2'
COLOR_TITLE_BG='#FF282828'
COLOR_STATUS_FG='#FFEBDBB2'
COLOR_STATUS_BG='#FF282828'
