#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# force numlock on during start
numlockx & 

# turn off this god-forsaken tap-to-click
# Note the very obviously named variable...
synclient MaxTapTime=0

# make sure xrdb has the most up-to-date settings
xrdb ~/.Xresources

# set our repeat rate
#xset r rate 190 40

# need to manually start pulseaudio
pulseaudio --start
pulseaudio-equalizer enable

# start xautlock to call slock after 10 minutes of inactivity OR if the mouse is
# left in the bottom-right corner for 3 seconds
#xautolock -time 10 -locker slock -nowlocker slock -detectsleep -corners 000+ -cornerdelay 3 &
xautolock -time 10 -locker slock -nowlocker slock -detectsleep &

# other incidentals
spotify &
blockify &
pasystray &
xbindkeys &

#exec startxfce4
#exec enlightenment_start
#startkde
exec ssh-agent i3
# ...or the Window Manager of your choice
