#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if [ -e ~/.xinitrc.local ]; then
  . ~/.xinitrc.local
fi

# DO THIS AT THE END: fire up window manager
# exec ssh-agent i3
exec ssh-agent openbox-session
