{
  imports = [
    ./aerospace.nix
    ./albert.nix
    ./atuin.nix
    ./browser.nix
    ./discord.nix
    ./easyeffects.nix
    ./firefox.nix
    ./fish.nix
    ./flameshot.nix
    ./fuzzel.nix
    ./gameglass.nix
    ./ghostty.nix
    ./git.nix
    ./gnome.nix
    ./helix.nix
    ./homelab.nix
    ./hyprland.nix
    ./jujutsu.nix
    ./keebs.nix
    ./kitty.nix
    ./nushell.nix
    ./nvim.nix
    ./obs.nix
    ./ranger.nix
    ./ssh.nix
    ./starcitizen.nix
    ./starsector.nix
    ./starship.nix
    ./swaylock.nix
    ./swappy.nix
    ./thunar.nix
    ./tmux.nix
    ./wezterm.nix
    ./yazi.nix
    ./zed-editor.nix
    ./zellij.nix
  ];
}
