{
  imports = [
    ./discord.nix
    ./easyeffects.nix
    ./face-tracking.nix
    ./firefox.nix
    ./fish.nix
    ./fuzzel.nix
    ./git.nix
    ./kitty.nix
    ./nushell.nix
    ./nvim.nix
    ./obs.nix
    ./ssh.nix
    ./starcitizen.nix
    ./starsector.nix
    ./starship.nix
    ./swappy.nix
    ./tmux.nix
    ./wezterm.nix
    ./zellij.nix
    ./zen-browser.nix
  ];
}
