abbr --add --global pac 'pacman'
abbr --add --global pacr 'pacman -R'
abbr --add --global pacrs 'pacman -Rs'
abbr --add --global pacrcs 'pacman -Rcs'
abbr --add --global pacs 'pacman -S'
abbr --add --global pacscc 'pacman -Scc'
abbr --add --global pacsyu 'pacman -Syu'
abbr --add --global pacsyy 'pacman -Syy'
abbr --add --global pacsyyu 'pacman -Syyu'
abbr --add --global supac 'sudo pacman'
abbr --add --global supacr 'sudo pacman -R'
abbr --add --global supacrs 'sudo pacman -Rs'
abbr --add --global supacrcs 'sudo pacman -Rcs'
abbr --add --global supacs 'sudo pacman -S'
abbr --add --global supacscc 'sudo pacman -Scc'
abbr --add --global supacsyu 'sudo pacman -Syu'
abbr --add --global supacsyy 'sudo pacman -Syy'
abbr --add --global supacsyyu 'sudo pacman -Syyu'
abbr --add --global supacu 'sudo pacman -U'
abbr --add --global supac.update "sudo pacman -Sy archlinux-keyring; and sudo pacman -Su"

abbr --add --global sc 'systemctl'
abbr --add --global sce 'systemctl enable --now'
abbr --add --global scd 'systemctl disable --now'
abbr --add --global scr 'systemctl restart'
abbr --add --global scs 'systemctl start'
abbr --add --global scst 'systemctl status'
abbr --add --global ssc 'sudo systemctl'
abbr --add --global ssce 'sudo systemctl enable'
abbr --add --global sscen 'sudo systemctl enable --now'
abbr --add --global sscd 'sudo systemctl disable'
abbr --add --global sscdn 'sudo systemctl disable --now'
abbr --add --global sscr 'sudo systemctl restart'
abbr --add --global sscs 'sudo systemctl start'
abbr --add --global sscst 'sudo systemctl status'

